targets:
  $default:
    builders:
      freezed:
        enabled: true
        generate_for:
          - lib/models/*.dart
      json_serializable:
        enabled: true
        generate_for:
          - lib/models/*.dart
