name: jaegram
description: JAEGram - Instagram etkileşim uygulaması (Gramelle/Topfollow benzeri)
version: 0.1.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0 # State yönetimi için
  hooks_riverpod: ^2.4.0 # For HookConsumerWidget and flutter_hooks
  flutter_hooks: ^0.20.5 # Required dependency for hooks
  provider: ^6.1.2 # Provider for state management
  web_socket_channel: ^2.4.0 # WebSocket support
  freezed_annotation: ^2.4.1 # Model sınıfları için (freezed_annotation versiyonu freezed ile uyumlu olmalı)
  json_annotation: ^4.8.1 # JSON serileştirme için (json_serializable ile uyumlu olmalı)
  http: ^1.2.0 # API istekleri için
  go_router: ^13.2.5 # Navigasyon için
  shared_preferences: ^2.2.2 # ADDED
  csv: ^5.1.1 # ADDED
  flutter_localizations: # Yerelleştirme için
    sdk: flutter 
  intl: ^0.20.2 # MODIFIED - Yerelleştirme için (flutter_localizations ile uyumlu)
  flutter_bootstrap: ^2.0.0 # Responsive tasarım için
  cached_network_image: ^3.3.1 # Uzaktan görseller için
  cupertino_icons: ^1.0.2
  fl_chart: ^0.66.2 # Fl_chart güncel versiyonu
  firebase_core: ^3.13.1 # Firebase güncel versiyonları
  firebase_messaging: ^15.2.6 # Firebase güncel versiyonları
  # background_fetch: ^1.3.8 # UNCOMMENTED
  app_links: ^3.5.1 # ADDED: uni_links yerine
  flutter_local_notifications: ^17.2.4 # UNCOMMENTED and UPDATED to a recent version
  badges: ^3.1.2
  image_picker: ^1.0.7 # ADDED for profile_screen.dart
  share_plus: ^7.2.2 # ADDED for admin_panel_screen.dart
  qr_flutter: ^4.1.0 # ADDED for 2FA QR codes
  timeago: ^3.6.0 # ADDED for notifications timestamp formatting
  timezone: ^0.9.2 # ADDED for notification scheduling with timezones
  flutter_staggered_grid_view: ^0.7.0 # ADDED for Instagram-style grid layout
  url_launcher: ^6.2.5 # ADDED for opening Instagram profile links

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8 
  freezed: ^2.5.8 # freezed versiyonu freezed_annotation ile uyumlu olmalı
  json_serializable: ^6.7.1 # JSON kod üretimi için (json_annotation ile uyumlu olmalı)
  integration_test:
    sdk: flutter
  flutter_gen_runner: ^5.3.2 # ADDED - Kod üretimi için (flutter_gen)

flutter:
  uses-material-design: true
  assets:
    - assets/jaegram_logo.png
    - assets/instagram_default_avatar.png
  generate: true # Bu satır flutter_localizations için l10n.yaml dosyasıyla birlikte kullanılır.

# flutter_gen yapılandırması (opsiyonel, assets vb. için)
# flutter_gen:
#   output: lib/generated/ # output directory for generated files
#   line_length: 80 # optional

#   integrations:
#     flutter_svg: true
#     flare_flutter: true
#     rive: true
#     lottie: true

# l10n.yaml dosyası oluşturulmalı (yerelleştirme için)
# Örnek l10n.yaml içeriği:
# arb-dir: lib/l10n 
# template-arb-file: app_en.arb
# output-localization-file: app_localizations.dart
# output-class: AppLocalizations # Bu sınıf adını kullanacağız
# preferred-supported-locales: [ en, tr ] # Desteklenen diller
