"""sync database schema with models

Revision ID: 03f62b82c8d8
Revises: 97c71a9135dc
Create Date: 2025-06-02 21:02:11.976923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f62b82c8d8'
down_revision: Union[str, None] = '97c71a9135dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_rewards', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_daily_rewards_id'), 'daily_rewards', ['id'], unique=False)
    op.create_index(op.f('ix_daily_rewards_user_id'), 'daily_rewards', ['user_id'], unique=False)
    op.drop_column('daily_rewards', 'reward_date')
    op.add_column('instagram_profiles', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('external_url', sa.String(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('category', sa.String(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('business_category_name', sa.String(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('business_phone', sa.String(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('business_email', sa.String(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('business_address_json', sa.Text(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('is_business_account', sa.Boolean(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('is_professional_account', sa.Boolean(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('professional_conversion_suggested', sa.Boolean(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('account_type', sa.String(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('avg_likes_per_post', sa.Integer(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('avg_comments_per_post', sa.Integer(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('engagement_rate', sa.String(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('post_frequency', sa.String(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('most_active_time', sa.String(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('most_active_day', sa.String(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('most_used_hashtags', sa.Text(), nullable=True))
    op.add_column('instagram_profiles', sa.Column('content_categories', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_profiles', 'content_categories')
    op.drop_column('instagram_profiles', 'most_used_hashtags')
    op.drop_column('instagram_profiles', 'most_active_day')
    op.drop_column('instagram_profiles', 'most_active_time')
    op.drop_column('instagram_profiles', 'post_frequency')
    op.drop_column('instagram_profiles', 'engagement_rate')
    op.drop_column('instagram_profiles', 'avg_comments_per_post')
    op.drop_column('instagram_profiles', 'avg_likes_per_post')
    op.drop_column('instagram_profiles', 'account_type')
    op.drop_column('instagram_profiles', 'professional_conversion_suggested')
    op.drop_column('instagram_profiles', 'is_professional_account')
    op.drop_column('instagram_profiles', 'is_business_account')
    op.drop_column('instagram_profiles', 'business_address_json')
    op.drop_column('instagram_profiles', 'business_email')
    op.drop_column('instagram_profiles', 'business_phone')
    op.drop_column('instagram_profiles', 'business_category_name')
    op.drop_column('instagram_profiles', 'category')
    op.drop_column('instagram_profiles', 'external_url')
    op.drop_column('instagram_profiles', 'full_name')
    op.add_column('daily_rewards', sa.Column('reward_date', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_daily_rewards_user_id'), table_name='daily_rewards')
    op.drop_index(op.f('ix_daily_rewards_id'), table_name='daily_rewards')
    op.alter_column('daily_rewards', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
